# Generated by Django 5.2.4 on 2025-08-04 19:47

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
